### DISCUSSION TITLE
Use existing reverse proxy, NPM

### DISCUSSION THREAD

**Discussion by mgrimace** [simonwep/ocular-docker#11] [Q&A] [answered]
Hi, 
Thank you for this, it looks exactly like what my family needs.

I use NPM as a reverse proxy for some existing services at home, typically using container_name:IP. I'm a copy/paste novice.

I see that Ocular has nginx in the compose.yaml already. If I want to use my own reverse proxy to self-host Ocular (say `budget.mydomain.com`), do I keep nginx in the compose.yaml and point NPM to nginx:80, or do I omit nginx from the compose.yaml and point NPM to frontend:(?port)? Either way, what changes (if any) are needed? 

Tl;dr, need help self-hosting properly with nginx in the mix.

**Comment by mgrimace** [comment, marked as answer]
Ok, as far as I can tell, nginx routes internally, and the easiest thing to do in my case is to keep the compose more or less as-is, and use NPM to proxy `budget.mydomain.com` to `ocular-nginx:80` assuming I set the container names as `ocular-frontend, ocular-backend, and ocular-nginx`.

**Reply by simonwep** [reply]
Hey! Iirc others had troubles with this, as I'm not familiar with _that_ NPM would you be interested in elaborating the problem you had and the solution so that we could add it to the [FAQ](https://github.com/simonwep/ocular-docker/blob/main/FAQs.md) for others? :)

**Reply by mgrimace** [reply]
Of course, 

Here's a quick FAQ where I was unclear, feel free to freely use/adapt/edit as you see fit:

### Should I use nginx in the docker compose.yaml file if I already have my own reverse proxy already set up? 
Yes, Ocular's nginx handles the _internal_ routing between the frontend and backend of Ocular. Your reverse proxy can be used to handle _external_ routing as usual.

### When reverse proxying Ocular, which Docker service do I point to: frontend, backend, or nginx?
Point your reverse proxy to Ocular's nginx, which in turn will handle routing between everything else. It may be helpful to use a `container_name` for Ocular's nginx to distinguish it from your own reverse proxy (e.g., `ocular-nginx`). If both your reverse proxy and Ocular are on the same docker network, you can use the container name `ocular-nginx` and its default internal port `80`, such as in the screenshot below (NPM):

![Screenshot 2025-02-16 101619](https://github.com/user-attachments/assets/f2ed13eb-0fab-4686-a74d-6f70a91a3cfb)

**Reply by simonwep** [reply]
Thank you! I'll add it to the FAQ soon, cheers! :)

**Comment by sdtm72** [comment]
Runs fine with npm only and proxy directly to front- and backend:

![Screenshot 2025-04-07 231038](https://github.com/user-attachments/assets/996987f3-cced-4010-8ad6-ee6f49acf2ba)
![Screenshot 2025-04-07 230824-1](https://github.com/user-attachments/assets/561fd5fc-1600-486f-b2aa-7f50eefbf6b1)

```
services:
  backend:
    image: ghcr.io/simonwep/genesis:v1.4.0
    restart: unless-stopped
    volumes:
      - ./data:/app/.data
    command: start
    environment:
      - GENESIS_PORT
      - GENESIS_DB_PATH
      - GENESIS_CREATE_USERS
      - GENESIS_AUTHORIZED_URIS
      - GENESIS_JWT_SECRET
      - GENESIS_JWT_TOKEN_EXPIRATION
      - GENESIS_JWT_COOKIE_ALLOW_HTTP
      - GENESIS_USERNAME_PATTERN
      - GENESIS_KEY_PATTERN
      - GENESIS_DATA_MAX_SIZE
      - GENESIS_KEYS_PER_USER
      - GENESIS_GIN_MODE
      - GENESIS_LOG_MODE

  frontend:
    image: ghcr.io/simonwep/ocular:v1.10.0
    restart: unless-stopped

```
