### ISSUE TITLE
ocular-docker-main-backend unhealty

### ISSUE THREAD

**Issue by smignon612** [simonwep/ocular-docker#1]
this container starts up but it is unhealty. i can see this fault : <html>
<body>

Connecting to localhost:8080 ([::1]:8080) wget: can't connect to remote host: Connection refused
--

</body>
</html>

data is not saved, i can put the admin password in but nothing happens to. (in oculus)

**Comment by simonwep** [comment]
Did you follow the step-by-step instructions in the readme? https://github.com/simonwep/ocular-docker?tab=readme-ov-file#setup It should work out of the box. I usually test it after each release, just checked, and it does work.

**Comment by smignon612** [comment]
well i did a wget of the repo, unzipped the fille and followed the steps., is wget the way to go?

**Comment by simonwep** [comment]
Yeah sure, that should work. What is your environment? The app should be accessible on localhost:3030, and what is the output if you run `docker compose up`?

**Comment by smignon612** [comment]
i run it on a lxc container (debian 12 bookworm,), tried also on alpina. 
root@ocular:~/ocular-docker-1.1.0# docker compose up -d
WARN[0000] /root/ocular-docker-1.1.0/docker-compose.yml: `version` is obsolete 
[+] Running 17/17
 ✔ nginx Pulled                                                                                                                                 24.1s 
   ✔ 3c854c8cbf46 Pull complete                                                                                                                  7.4s 
   ✔ de5d475193dd Pull complete                                                                                                                  9.6s 
   ✔ b407bcc80638 Pull complete                                                                                                                  9.8s 
   ✔ da33b1ad0ac4 Pull complete                                                                                                                  9.9s 
   ✔ a0fbd691d7c1 Pull complete                                                                                                                 10.1s 
   ✔ 16eaaaf5f1c0 Pull complete                                                                                                                 10.2s 
   ✔ 5e845cc16269 Pull complete                                                                                                                 11.8s 
 ✔ backend Pulled                                                                                                                               22.0s 
   ✔ 96526aa774ef Pull complete                                                                                                                  7.0s 
   ✔ d351360294b2 Pull complete                                                                                                                  7.2s 
   ✔ 99ba685f8f11 Pull complete                                                                                                                 15.1s 
 ✔ frontend Pulled                                                                                                                              13.8s 
   ✔ d6e6e2f0bb21 Pull complete                                                                                                                  6.0s 
   ✔ 90b0f82a5404 Pull complete                                                                                                                  6.3s 
   ✔ d76632970659 Pull complete                                                                                                                  6.8s 
   ✔ 00dd356aa92e Pull complete                                                                                                                  6.9s 
[+] Running 4/4
 ✔ Network ocular-docker-110_ocular        Created                                                                                               0.1s 
 ✔ Container ocular-docker-110-frontend-1  Started                                                                                               1.1s 
 ✔ Container ocular-docker-110-backend-1   Started                                                                                               1.2s 
 ✔ Container ocular-docker-110-nginx-1     Started                                                                                               1.3s 

CONTAINER ID   IMAGE                            COMMAND                  CREATED         STATUS                     PORTS                  NAMES
c260a245beec   nginx:1.24-alpine                "/docker-entrypoint.…"   3 minutes ago   Up 3 minutes               0.0.0.0:3030->80/tcp   ocular-docker-110-nginx-1
4991b82db595   ghcr.io/simonwep/ocular:v1.4.0   "busybox httpd -v -f"    3 minutes ago   Up 3 minutes (healthy)     80/tcp                 ocular-docker-110-frontend-1
30d84d4175c1   ghcr.io/simonwep/genesis:v0.2    "./genesis"              3 minutes ago   Up 3 minutes (unhealthy)   8080/tcp               ocular-docker-110-backend-1

i can access the webpage via the adress of the server and port, i can give the admin login and pasw, but there it stops :( 
i noticed the bachend container had the same ip as portrainer, so relaunched a lxc container without portrainer but some error

**Comment by simonwep** [comment]
> i can access the webpage via the adress of the server and port, i can give the admin login and pasw, but there it stops :(

What exactly stops? The containers crash? Can you log in? Or is just the container unhealthy? I never worked with LXC containers... so I can't give you any help with that.

> i noticed the backend container had the same ip as portrainer, so relaunched a lxc container without portrainer but some error  

What error? You can modify the ports in `docker-compose.yml` and the nginx config as you wish, but normally you won't have to change anything.

**Comment by simonwep** [comment]
I just noticed that the bridged network is redundant, can you try it with the following `docker-compose.yml`?

```yml
services:
  backend:
    image: ghcr.io/simonwep/genesis:v0.2
    restart: unless-stopped
    volumes:
      - ./data:/app/.data
    environment:
      - GENESIS_PORT
      - GENESIS_DB_PATH
      - GENESIS_CREATE_USERS
      - GENESIS_AUTHORIZED_URIS
      - GENESIS_JWT_SECRET
      - GENESIS_JWT_TOKEN_EXPIRATION
      - GENESIS_USERNAME_PATTERN
      - GENESIS_KEY_PATTERN
      - GENESIS_DATA_MAX_SIZE
      - GENESIS_KEYS_PER_USER
      - GENESIS_GIN_MODE
      - GENESIS_LOG_MODE

  frontend:
    image: ghcr.io/simonwep/ocular:v1.4.0
    restart: unless-stopped

  nginx:
    image: nginx:1.24-alpine
    restart: unless-stopped
    ports:
      - "3030:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
```
